import datetime

def printJobStart(jobname):
    now = datetime.datetime.now()
    print("")
    print(" ________  _____ ______   ___  ___      ")
    print("|\   ____\|\   _ \  _   \|\  \|\  \     ")
    print("\ \  \___|\ \  \ \__\ \  \ \  \ \  \    ")
    print(" \ \  \    \ \  \ |__| \  \ \  \ \  \   ")
    print("  \ \  \____\ \  \    \ \  \ \  \ \  \  ")
    print("   \ \_______\ \__\    \ \__\ \_______\ ")
    print("    \|_______|\|__|     \|__|\|_______| ")
    print("")
    print("CARNEGIE MELLON UNIVERSITY - HEINZ COLLEGE")
    print("95797-Z5: DATA WAREHOUSING")
    print("Group 8 Project: ")
    print("SPARCS (Statewide Planning and Research Cooperative System)")
    print("")
    print("*****************************    ******************************")
    print("*********************                    **********************")
    print("*************                                    **************")
    print("*********                                            **********")
    print("          "+ jobname +" Started @ "+ now.strftime("%Y/%m/%d - %H:%M:%S") +"")
    print("*********                                            **********")
    print("*************                                    **************")
    print("*********************                    **********************")
    print("*****************************    ******************************")
    print("")

def printJobEnd(jobname):
    now = datetime.datetime.now()
    print("")
    print("*****************************    ******************************")
    print("*********************                    **********************")
    print("*************                                    **************")
    print("*********                                            **********")
    print("          "+ jobname +" Ended   @ "+ now.strftime("%Y/%m/%d - %H:%M:%S") +"")
    print("*********                                            **********")
    print("*************                                    **************")
    print("*********************                    **********************")
    print("*****************************    ******************************")
    print("")

def printStepStart(stepNo):
    now = datetime.datetime.now()
    print("")
    print("")
    print("# Beginning JS " + stepNo + " @ " + now.strftime("%Y%m%d:%H%M%S"))
    print("###########################################################")
    print("")
